# Generated by Django 3.2.5 on 2021-07-14 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20210713_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='countent',
            new_name='content',
        ),
    ]
